package esz.dev.user.config;

import com.google.inject.AbstractModule;
import esz.dev.user.control.UserMapper;
import esz.dev.user.control.UserMapperImpl;

/**
 * Configuration for Guice to be able to inject mappers generated by MapStruct.
 */
public class UserMapperConfig extends AbstractModule {
    @Override
    protected void configure() {
        bind(UserMapper.class).to(UserMapperImpl.class);
    }
}
